Known regressions from Python 2.x to the py3k branch that aren't currently covered by the test suite:

   * Calling dir() on a traceback instance produces an empty list; in 2.x, it worked correctly.
